#################### default parameters ################################
# favicon
favicon = "images/lezzet-favicon.png"

# logo
logo = "images/lezzet-logo.png"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "200px"

# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true

# logo text will only show when logo is missing.
logo_text = "Lezzet Turkish Brunch"

# purgeCSS
purge_css = true

# search
search = false

# Main Sections
mainSections = ["blog"]

# image gallery shortcode
image_gallery = false

# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# copyright
copyright = "Copyright Lezzet Turkish Brunch"
design_by = "[Forrtek Solutions](https://forrtek.com)"

# Preloader
[preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "sign up"
link = "#"

# contact info
[contact_info]
address = "12722 SE 312th St Suite H Auburn, WA 98092"
address_link = "https://g.page/r/CQbki5MuvLeLEBA"
mobile = "(253) 737-4601"

# google_map
[google_map]
enable = true
embed_url = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2704.5663383819883!2d-122.17188619999997!3d47.322809899999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x549059005deccd71%3A0x8bb7bc2e938be406!2sLezzet%20Brunch!5e0!3m2!1sen!2sus!4v1714780573976!5m2!1sen!2sus"

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["turkish", "brunch", "auburn", "kent"]
description = "Lezzet Turkish Brunch is a Turkish Restaurant in Auburn, WA 98092"
author = "Forrtek Solutions"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "pinterest"
icon = "fab fa-pinterest" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.pinterest.com/LezzetBrunch/"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/lezzetbrunch/"


[[social]]
title = "google"
icon = "fab fa-google" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://g.page/r/CQbki5MuvLeLEBA"

[[social]]
title = "yelp"
icon = "fab fa-yelp" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.yelp.com/biz/lezzet-brunch-auburn-2"

############################## business hours ###########################

[[business_hours]]
day = "Monday"
time = "CLOSED"

[[business_hours]]
day = "Tuesday"
time = "8AM - 4PM"
[[business_hours]]
day = "Wednesday"
time = "8AM - 4PM"

[[business_hours]]
day = "Thursday"
time = "8AM - 4PM"

[[business_hours]]
day = "Friday"
time = "8AM - 4PM"

[[business_hours]]
day = "Saturday"
time = "9AM - 5PM"

[[business_hours]]
day = "Sunday"
time = "9AM - 5PM"